// <auto-generated />
using CityInfoApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfoApi.Migrations
{
    [DbContext(typeof(CityInfoApiContext))]
    [Migration("20250521065142_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CityInfoApi.Entity.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Madurai is famous for everything",
                            Name = "Madurai"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Coimbatore is famous for Slang",
                            Name = "Coimbatore"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Theni is a place of nature",
                            Name = "Theni"
                        });
                });

            modelBuilder.Entity("CityInfoApi.Entity.PointOfInterestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Vadipatti is a small town in Madurai district",
                            Name = "Vadipatti"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Madurai is a city in Tamil Nadu",
                            Name = "Solavanthan"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Pollachi is for Kongu culture and traditions",
                            Name = "Pollachi"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Metupalayam is a small town in Coimbatore district",
                            Name = "Metupalayam"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Cumbam is a small town in Theni district where sree praveen lives",
                            Name = "Cumbam"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "Chinnamanur is a small town in Theni district where sudhan siva lives",
                            Name = "Chinnamanur"
                        });
                });

            modelBuilder.Entity("CityInfoApi.Entity.PointOfInterestEntity", b =>
                {
                    b.HasOne("CityInfoApi.Entity.CityEntity", "City")
                        .WithMany("PointOfInterestEntities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfoApi.Entity.CityEntity", b =>
                {
                    b.Navigation("PointOfInterestEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
